services:
  - type: web
    name: imei-checker-app
    env: node
    buildCommand: ./render-build.sh
    startCommand: node scripts/au_checker.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_DOWNLOAD_PATH
        value: /opt/render/.cache/puppeteer
