services:
  - type: web
    name: imei-checker-app
    env: ruby
    buildCommand: ./render-build.sh
    startCommand: ruby bin/rails server -b 0.0.0.0

    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_DOWNLOAD_PATH
        value: /opt/render/.cache/puppeteer
      - key: CHROME_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.70/chrome-linux64/chrome
